<?xml version="1.0" encoding="UTF-8"?>

<!DOCTYPE catalogo [
        <!ELEMENT catalogo (producto)*>

        <!ELEMENT producto (nombre, descripcion, precio)>
        <!ELEMENT nombre (#PCDATA)>
        <!ELEMENT precio (#PCDATA)>
        <!ELEMENT descripcion (#PCDATA)*>
        <!ELEMENT caracteristicas (caracteristica)>
        <!ELEMENT caracteristica (#PCDATA)>
]>
<catalogo>
        <producto>
                <nombre>Impresora</nombre>
                <descripcion>Impresora a color o blanco y negro</descripcion>
                <precio>40$</precio>
                <!-- <caracteristicas tipo="calidad">- mas de 200 folios la hora y silenciosa</caracteristicas>
                <caracteristicas>- Conexion bluetooth</caracteristicas> -->
        </producto>
        <producto>
                <nombre>Monitor</nombre>
                <descripcion>Imagen 4K y curvo</descripcion>
                <precio>70$</precio>
                <!-- <caracteristicas tipo="calidad">- mas de 200 folios la hora y silenciosa</caracteristicas>
                <caracteristicas>- Conexion bluetooth</caracteristicas> -->
        </producto>
</catalogo>
