<?xml version="1.0" encoding="UTF-8"?>

<!-- En un departamento se ha decidido la siguiente estructura para ficheros de datos que se tengan que mover 
de unos software a otros.
La raíz debe ser el elemento <listacompras>
Dentro de <listacompras> debe haber uno o más elementos <venta>
Una venta puede llevar dentro uno de dos: <ventaacredito> o <ventainmediata>
Un elemento <ventaacredito> consta de : un elemento <fechafinpago> que es optativo y un elemento <cantidad> 
que es obligatorio.
Un elemento <ventainmediata> lleva dentro dos cosas: un elemento <cantidad> que es obligatorio y 
un elemento <divisa> que también es obligatorio. -->
<!DOCTYPE listacompras [
    <!ELEMENT listacompras (venta+)>
    <!ELEMENT venta (ventacredito | ventainmediata)>
    <!ELEMENT ventacredito (fechafinpago? , cantidadCredito)>
    <!ELEMENT fechafinpago (#PCDATA)>
    <!ELEMENT cantidadCredito (#PCDATA)>
    <!ELEMENT ventainmediata (cantidad, divisa)>
    <!ELEMENT cantidad (#PCDATA)>
    <!ELEMENT divisa (#PCDATA)>
]>
<listacompras>
    <venta>   
        <ventacredito>   
            <fechafinpago></fechafinpago>  
            <cantidadCredito>88</cantidadCredito>
        </ventacredito>
    </venta>
    <venta>
        <ventainmediata>
            <cantidad>15</cantidad>
            <divisa>MasterCard</divisa>
        </ventainmediata>
    </venta>
</listacompras>
