<?xml version="1.0" encoding="UTF-8"?>
<!-- La Seguridad Social necesita un formato de intercambio unificado para distribuir la información personal de los afiliados.
Todo archivo XML contiene un listado de uno o mas afiliados
Todo afiliado tiene los siguientes elementos:
DNI o NIE
Nombre
Apellidos
Situación laboral: que tiene que ser una y solo una de entre estas posibilidades: «en_paro», «en_activo», 
«jubilado», «edad_no_laboral»
Fecha de nacimiento: que se desglosa en los elementos obligatorios día, mes y anio.
Listado de bajas: que indica las situaciones de baja laboral del empleado. 
Dicho listado consta de una repetición de 0 o más bajas:
Una baja consta de tres elementos: causa (obligatoria), fecha de inicio (obligatorio) y fecha de final (optativa),
Listado de prestaciones cobradas: consta de 0 o más elementos prestación, donde se indicará la cantidad percibida (obligatorio), 
la fecha de inicio (obligatorio) y la fecha de final (obligatorio) -->
<!DOCTYPE afiliados [
<!ELEMENT afiliados (afiliado)+>
<!ELEMENT afiliado ((dni | nie), nombre, apellidos, situacionLaboral)>
<!ELEMENT dni (#PCDATA)>
<!ELEMENT nie (#PCDATA)>
<!ELEMENT nombre (#PCDATA)>
<!ELEMENT apellidos (#PCDATA)>
<!ELEMENT situacionLaboral (enParo | enActivo | jubilad | edadNoLaboral)>
<!ELEMENT enParo EMPTY>
<!ELEMENT fechaNacimiento (dia, mes, anio)>
<!ELEMENT dia (#PCDATA)>
<!ELEMENT mes (#PCDATA)>
<!ELEMENT anio (#PCDATA)>
<!ELEMENT listadoBajas (bajas*)>
<!ELEMENT bajas (causa, fechaDeInicio, fechaFinal)>
<!ELEMENT causa (#PCDATA)>
<!ELEMENT fechaDeInicio (#PCDATA)>  
<!ELEMENT fechaFinal (#PCDATA)>
]>
<afiliados>
    <afiliado>
        <dni>123456789J</dni>
        <nie></nie>
        <nombre>Pepito </nombre>
        <apellidos>Ramirez</apellidos>
            <situacionLaboral>
                <enParo></enParo>
            </situacionLaboral>
        <fechaNacimiento>
            <dia>12</dia>
            <mes>04</mes>
            <anio>1892</anio>
        </fechaNacimiento>
        <listadoBajas>
            <bajas>
            <causa>Esguince</causa>
            <fechaDeInicio>02/09/2023</fechaDeInicio>
            <fechaFinal>15/09/2023</fechaFinal>
        </bajas>
        </listadoBajas>
    </afiliado>
</afiliados>